name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Fetch My Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: sunnydanu/waka-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE : "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_OS: "False"