name: Waka Readme

on:
  push:
      branches:
        - master
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
   update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: aaditkamat/waka-readme-stats@generate-html-stats #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: FALSE
          SHOW_LINES_OF_CODE: TRUE
          SHOW_LOC_CHART: TRUE
          LOCALE: "en"
        
         