name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Fetch My Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: sunnydanu/waka-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE: "False"  
          SHOW_LINES_OF_CODE: "True"
        
          
