name: Waka Stats

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: Fetch My Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: sunnydanu/waka-stats@v3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT : "False"
          SHOW_PROJECTS  : "False"
          SHOW_TIMEZONE   : "False"
          SHOW_EDITORS    : "False"
          SHOW_LANGUAGE_PER_REPO   : "False"


